---
title: "Отчёт"
output: word_document
date: "2026-01-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```
```{r}
if (!require("pastecs")) install.packages("pastecs")
library(pastecs)
```

```{r load}
raw_data <- read.csv("data/original/team6_ecrf_wide.csv")
```

# Характеристики пациентов
## Демография и иные исходные характеристики

```{r dm}

```

# Анализ эффективности
## Интенсивность боли по ВАШ (в покое)

```{r VAS_prep}
prep_VAS <- raw_data %>% 
  select(c(contains("VAS"), USUBJID, ARM)) %>% 
  pivot_longer(cols = starts_with("V"),
    names_to = c("VISIT", "CONDITION"),
    names_pattern = "(V\\d)_PAIN_VAS(.*)",
    values_to = "VALUE")

bl_VAS <- prep_VAS %>% 
  filter(VISIT=="V1") %>% 
  mutate(BLVALUE=VALUE) %>% 
  select(-c(VISIT, VALUE, ARM))


final_VAS <- prep_VAS %>% 
  left_join(bl_VAS, join_by(USUBJID, CONDITION)) %>% 
  mutate(BLFL=ifelse(VISIT=="V1", 1, 0),
         CHVALUE=ifelse(BLFL==0, BLVALUE-VALUE, NA_real_),
         VISIT=as.factor(VISIT))

final_VAS_total <- rbind(final_VAS, mutate(final_VAS, ARM = "Total"))

```


```{r VAS_rest}
library(flextable)
globaldec <- ","
globaldig <- 2

f_num <- function(x, dig = globaldig, dec = globaldec, p = FALSE, pre = "", suf = "") {
        n <- formatC(x, digits = dig, decimal.mark = dec, format = "f")
        n <- ifelse(p == TRUE & x < 0.001, paste0("<0", dec, strrep("0", dig-1), "1"), n)
        n <- ifelse(p == TRUE & x == 1, paste0(">0", dec, strrep("9", dig)), n)
        n <- paste0(pre, n, suf)
        return(n)
}

statlist <- c(
        `Количество наблюдений` = "nbr.val",
        `Среднее (СО)` = "mean.std",
        `97.5% ДИ` = "CI.mean",
        `Медиана (Q1; Q3)` = "median.q1.q3",
        `Минимум – Максимум` = "minmax")

sumnum <- function(x, stats = statlist, conflev=.975)
{
        std <- stat.desc(as.numeric(x), p=conflev)
        
        CI.L  <- std["mean"] - std["CI.mean.0.975"]
        CI.U  <- std["mean"] + std["CI.mean.0.975"]
        
        Q.L <- quantile(x, probs = 0.25, na.rm = TRUE)
        Q.U <- quantile(x, probs = 0.75, na.rm = TRUE)
        
        std <- c(std, CI.L = CI.L, CI.U = CI.U, Q.L = Q.L, Q.U = Q.U)
        
        std[-c(1:3)] <- f_num(std[-c(1:3)])
        
        std <- gsub(pattern = ".*N.*|.*I.*", replacement = "-", std)
        
        std["mean.std"] = paste0(std["mean"], " (", std["std.dev"], ")")
        std["CI.mean"] = paste(std["CI.L.mean"], std["CI.U.mean"], sep = " - ")
        std["median.q1.q3"] = paste0(std["median"], " (", paste(std["Q.L.25%"], std["Q.U.75%"], sep = "; "), ")")
        std["minmax"] = paste(std["min"], std["max"], sep = " - ")

        std <- std[stats] %>% rbind() %>% as.data.frame() 
        colnames(std) <- names(stats)
        
        return(std)
}

describe_num <- function (data, idvar, grvar, visvar, grcodes, 
                          varcodes, varnames, visits, total = NULL, 
                          col_name=varnames) {
        dat <- data %>%
                as.data.frame() %>% 
                select(all_of(c(ID = idvar, GROUP = grvar, VISIT = visvar)), all_of(varcodes))
        
        # Суммарные данные
        if (!is.null(total)) dat <- rbind(dat, mutate(dat, GROUP = factor(total)))
        
        # Расчет описательной статистики
        ltbl <- dat %>%
                complete(GROUP, VISIT) %>%
                filter(VISIT %in% visits) %>%
                mutate(across(.cols = all_of(varcodes), .fns = as.numeric)) %>% 
                pivot_longer(cols = all_of(varcodes), names_to = "VAR", values_to = "VAL", 
                             names_transform = list(VAR = fct_inorder)) %>% 
                mutate(VAL = as.numeric(VAL), VISIT = droplevels(VISIT)) %>%
                group_by(VAR, VISIT, GROUP) %>%
                do(sumnum(.$VAL)) # sumnum.R
        
        # Набор данных с описательной статистикой
        ttbl <- ltbl %>% 
                pivot_longer(cols = c(-VAR, -VISIT, - GROUP), names_to = "PARAM", values_to = "VAL", 
                             names_transform = list(PARAM = fct_inorder)) %>% 
                arrange(VAR, VISIT, GROUP, PARAM) %>% 
                ungroup() %>% 
                mutate(VAR = case_when(VAR=={{varcodes}}~{{col_name}}), 
                       VAR = factor(VAR, levels = varnames))
        
        return(ttbl)
}


idvar <- "USUBJID" 
grvar <- "ARM" 
visvar <- "VISIT"
grcodes <- c("Траумель"="Traumeel", "Диклофенак"="Diclofenac")
vis_codes <- c("Визит 1\n(исходный уровень"="V1",
               "Визит 2"="V2",
               "Визит 3"="V3")

vis_codes <- c("V1"="Визит 1\n(исходный уровень",
               "V2"="Визит 2",
               "V3"="Визит 3")

# vis_codes <- c("V1",
#                "V2",
#                "V3")

visits <- c("Визит 1\n(исходный уровень)",
            "Визит 2",
            "Визит 3")

visits <- c("V1", "V2", "V3")
# colslist <- c(
#         `Показатель` = "VAR", 
#         `Визит`      = "VISIT", 
#         `Группа`     = "GROUP", 
#         `Параметр`   = "PARAM", 
#         `Сравнение`  = "P"
# )
NA_label <- "–"
bgp_label <- "p-value (между группами)"
wgp_label <- "p (с начальным уровнем)"
```


```{r VAS_rest}
my_data <- final_VAS %>% filter(CONDITION=="REST") %>% mutate(ARM=fct_relevel(ARM, "Traumeel", "Diclofenac"))

varcodes <- "VALUE" 
varnames <- "Наблюдаемое значение" 
res_obs <- describe_num(my_data, idvar, grvar, visvar, grcodes, 
                    varcodes, varnames, visits, total = "Все пациенты", 
                    col_name="Наблюдаемое значение")

varcodes <- "CHVALUE" 
varnames <- "Изменение от исходного уровня" 
res_ch <- describe_num(my_data, idvar, grvar, visvar, grcodes, 
                    varcodes, varnames, visits, total = "Все пациенты", 
                    col_name="Изменение от исходного уровня") %>% 
  rowwise() %>% 
  mutate(VAL=ifelse(VISIT=="V1", "-", VAL)) %>% 
  ungroup()

t_test_result_v2 <- t.test(CHVALUE ~ ARM, data = subset(my_data, VISIT=="V2"), var.equal = T, conf.level=.975, alternative = "greater", mu=-6.5)$p.value

t_test_result_v3 <- t.test(CHVALUE ~ ARM, data = subset(my_data, VISIT=="V3"), var.equal = T, conf.level=.975, alternative = "greater", mu=-6.5)$p.value
glimpse(my_data)
t.test(CHVALUE ~ ARM, data = subset(my_data, VISIT=="V3"), var.equal = T, conf.level=.975, alternative = "greater", mu=-6.5)$conf.int

library(broom)
result_df <- t.test(CHVALUE ~ ARM, data = subset(my_data, VISIT=="V3"), var.equal = T, conf.level=.975, alternative = "greater", mu=-6.5) %>%
  tidy() %>%
  mutate(
    ci_formatted = sprintf("%.1f - %.1f", conf.low, conf.high)
  ) %>%
  select(estimate, p.value, ci_formatted)

result <- t.test(CHVALUE ~ ARM, data = subset(my_data, VISIT=="V3"), var.equal = T, conf.level=.975, alternative = "greater", mu=-6.5) %>%
  tidy() %>%
  mutate(
    # Форматируем: Оценка (Нижняя - Верхняя)
    formatted_output = sprintf("%.1f (97.5%% ДИ %.1f - %.1f)", 
                               estimate, conf.low, conf.high)
  )

results <- my_data %>%
  filter(VISIT!="V1") %>% 
  group_by(VISIT) %>%
  nest() %>%
  mutate(
    ttest = map(data, ~t.test(CHVALUE ~ ARM, data = .x, conf.level = 0.975, alternative = "greater", mu=-6.5) %>% tidy())
  ) %>%
  unnest(ttest) %>%
  mutate(
    `Оценка (97.5% ДИ)` = sprintf("%.1f (%.1f - %.1f)", estimate, conf.low, conf.high)
  ) %>%
  mutate(VISIT = case_match(VISIT,
                            "V2" ~ "Между визитами 1 и 2",
                            "V3" ~ "Между визитами 1 и 3",
                            .default = VISIT),
         `p-value`=round(p.value, 3) %>% as.character(),
         estimate1=round(estimate1, 2),
         estimate2=round(estimate2, 2)
         ) %>% 
  select(VISIT, `p-value`, `Оценка (97.5% ДИ)`, estimate1, estimate2) %>%
  rename(`Траумель`=estimate1, `Диклофенак`=estimate2, `Изменение интенсивности боли по ВАШ (мм)`=VISIT) %>% 
  
  


```


```{r VAS_rest}
# maketable_num <- function(data, idvar, grvar, visvar, grcodes, varcodes, varnames, visits, total = NULL, by = "VAR",
#                           between = NULL, within = NULL, baseline = NULL, table_cols = colslist, dropcols = NULL)
# {
#         ftable <- describe_num(data, idvar, grvar, visvar, grcodes, varcodes, varnames, visits, total = total)
#         ftable <- ftable %>% select(any_of(unname(table_cols)), everything()) %>% arrange(across(1:4))
#         
#         if (is.function(between)) {
#                 
#                 ctable <- compare_between(data, idvar, grvar, visvar, grcodes, varcodes, varnames, visits, fun = between)
#                 ftable <- bind_rows(ftable, ctable) %>% select(all_of(unname(table_cols)), everything()) %>% arrange(across(1:4))
#                 ftable <- ftable %>% mutate(VAL = coalesce(VAL, P)) %>% select(-P)
#                 
#         } # between
#         
#         if (is.function(within)) {
#                 
#                 wtable <- compare_within(data, idvar, grvar, visvar, grcodes, varcodes, varnames, visits, fun = within, 
#                                          baseline = baseline)
#                 levels(wtable$GROUP) <- c(grcodes, total)
#                 ftable <- bind_rows(ftable, wtable) %>% select(all_of(unname(table_cols)), everything()) %>% arrange(across(1:4))
#                 ftable <- ftable %>% mutate(VAL = coalesce(VAL, P)) %>% select(-P)
#                 
#         } # within
#         
#         if (by == "VAR") { # Привести в столбцах показатели
#                 
#                 ftbl <- ftable %>% spread(VAR, VAL)
#                 
#         } else if (by == "VISIT") { # Привести в столбцах визиты
#                 
#                 ftbl <- ftable %>% spread(VISIT, VAL)
#                 
#         } else if (by == "PARAM") { # Привести в столбцах статистику
#                 
#                 ftbl <- ftable %>% filter(!is.na(GROUP)) %>% mutate(PARAM = fct_na_value_to_level(PARAM, wgp_label)) %>%  
#                         spread(PARAM, VAL)
#                 
#                 if (is.function(between)) ftbl <- ftbl %>% full_join(ctable, by = c("VAR", "VISIT"))
#                 
#         } else if (by == "GROUP") { # Привести в столбцах группы
#                 
#                 ftbl <- ftable %>% filter(!is.na(GROUP)) %>% mutate(PARAM = fct_na_value_to_level(PARAM, wgp_label)) %>% 
#                         spread(GROUP, VAL)
#                 
#                 if (is.function(between)) ftbl <- ftbl %>% full_join(ctable, by = c("VAR", "VISIT"))
#         }
#         
#         ftbl <- ftbl %>% mutate(across(.cols = everything(), .fns = as.character)) %>% as.data.frame()
#         
#         ftbl[rowSums(is.na(ftbl[2:3])) == 2, 2:3] <- bgp_label
#         ftbl[is.na(ftbl[3]), 3] <- wgp_label
#         
#         ftbl <- ftbl %>% rename(any_of(table_cols)) %>% as.data.frame()
#         
#         return(
#                 f_tab(ftbl, dropcols = dropcols, 
#                       mergecols = colnames(ftbl)[colnames(ftbl) %in% names(table_cols)], mergerows = bgp_label)
#         )
# }
# 
# compare_between <- function(data, idvar, grvar, visvar, grcodes, varcodes, varnames, visits, 
#                             fun = btw_2gr_num, catcodes = NULL)
# {
#         environment(fun) <- environment()
#         
#         dat <- data %>%
#                 as.data.frame() %>%
#                 select(all_of(c(ID = idvar, GROUP = grvar, VISIT = visvar)), all_of(varcodes)) %>%
#                 filter(VISIT %in% visits)
#         
#         # Именованный список наборов данных по переменным
#         var_lst <- map(set_names(varcodes), ~ select(dat, ID, VISIT, GROUP, VAL = all_of(.x)))
#         
#         # Вложенный список наборов данных по визитам
#         vis_lst <- map(var_lst, ~ split(.x, .x$VISIT, drop = TRUE))
#         
#         # Применение функции
#         p_lst <- vis_lst %>% map(~ map(.x, fun))
#         
#         # Набор данных со значениями p-value
#         ptbl <- p_lst %>%
#                 set_names(varnames) %>% map(bind_rows) %>% bind_rows(.id = "VAR") %>%
#                 pivot_longer(cols = -VAR, names_to = "VISIT", values_to = "P") %>%
#                 mutate(
#                         VISIT = factor(VISIT, levels = visits),
#                         VAR = factor(VAR, levels = varnames)
#                 )
#         
#         return(ptbl)
# }
# 
# btw_2gr_num <- function(dt, silently = T) {
#         
#         pv <- tryCatch( # tryCatch
#                 {
#                   dt <- dt %>% mutate(VAL = as.numeric(VAL), GROUP = droplevels(GROUP))
#                   tr <- t.test(VAL ~ GROUP, dt, var.equal = T, conf.level=.975, alternative = "greater", mu=-6.5)$p.value
#                   pv <- f_num(tr, 3, p = T, suf = ifelse(round(tr, 3) < 0.025, "*", ""))
#                         
#                   pv
#                 },
#                 error = function(e)
#                 {
#                   if (silently == FALSE) cat(" Error -----", e$message, "\n")
#                   return(NA_label)
#                 }
#         ) # tryCatch
#         
#         return(pv)
# }
# 
# f_tab <- function (table, size = 8, dropcols = NULL, mergecols = NULL, mergerows = NULL) 
# {
#         table <- table %>% select(-any_of(dropcols))
#         
#         # indexes for horizontal merging
#         ind <- map(mergerows, ~which(table == ., arr.ind = TRUE) %>% as.data.frame()) %>% bind_rows()
#         
#         ftbl <- table %>% 
#                 flextable() %>% 
#                 theme_box() %>% 
#                 font(fontname = "Times New Roman", part = "all") %>% 
#                 fontsize(size = size, part = "all") %>% 
#                 align(align = "center", part = "all") %>% 
#                 # vertical merging
#                 merge_v(j = colnames(table) %in% mergecols)
#         
#         # horizontal merging
#         if (length(ind) == 2) {for (i in unique(ind$row)) ftbl <- merge_at(ftbl, i = i, j = unique(ind$col[ind$row == i]))}
#         
#         return(ftbl)
# }
# 
# ftable_obs_PEP_w <- maketable_num(
#         my_data, idvar, grvar, visvar, grcodes, varcodes, varnames, visits, # это то, что мы уже задали
#         total = "Все пациенты", # если есть несколько групп - указывает статистику в целой популяции
#         by = "PARAM", # метод построения таблицы: в колонках переменные, в строках визиты (может ещё быть "VISIT", "GROUP", "PARAM")
#         between = btw_2gr_num, within = NULL, # сравнения между группами или внутри группы в динамике
#         baseline = "V1"
# )
```

## Интенсивность боли по ВАШ (после нагрузки)

```{r VAS_20m}

```

# Анализ безопасности
## ЭКГ

```{r ecg}

```

## Клинический анализ крови

```{r oak}

```

## Жизненно-важные показатели

```{r vs}

```

